### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by luantunez** [FabioTomaz/msc#1]
Hello and thank you for your work!
Would it be possible for you to provide the pretrained model checkpoint?
Thank you in advance, Lucia

**Comment by FabioTomaz** [comment]
Hello Lucia,

Unfortunately, I cannot provide you any of the pre-trained models, as I've lost access to the computer (from my university) where I was training these models. However, some of the smaller pre-trained models like the VGG16 can be easily trained on most computers with the same hyperparameters as described in the thesis document. Let me know if you need help replicating some of this work.

Hope it helps,
Fabio
